baseURL = "https://mcclatchy.github.io/design"
title = "McClatchy Design"

languageCode = "en-us"
relativeURLs = true
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsStyle = "borland"

disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[menu]
  [[menu.main]]
    name = "about us"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "style guide"
    url = "/saratoga/"
    weight = 3
