baseURL = "https://mjs2430.github.io/"
title = "McClatchy Design"
publishDir = "mjs2430.github.io"

languageCode = "en-us"
relativeURLs = true
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsStyle = "borland"
disableLiveReload = true

disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "404"]

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "style guide"
    url = "/saratoga/"
    weight = 1
  [[menu.main]]
    name = "markets"
    url = "/markets/"
    weight = 2
  [[menu.main]]
    name = "ads"
    url = "/ads/"
    weight = 3
  [[menu.main]]
    name = "labs"
    url = "/labs/"
    weight = 4
