baseURL = "https://mcclatchy.github.io/design"
title = "McClatchy Design"

languageCode = "en-us"
relativeURLs = true
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsStyle = "borland"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "about us"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "blog"
    url = "https://medium.com/mcclatchy-design"
    weight = 3
  [[menu.main]]
    name = "style guide"
    url = "/saratoga/"
    weight = 4
