# Globals
baseURL = "https://mcclatchy.github.io/design"
title = "McClatchy Design"
languageCode = "en-us"
relativeURLs = true
pluralizeListTitles = false
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "404"]

# Highlighting
pygmentsCodeFences = true
pygmentsStyle = "borland"

# Markdown Options
[markup.goldmark.renderer]
  unsafe = true

# Top Nav menu
[[menu.main]]
  name = "style guide"
  url = "/saratoga/"
[[menu.main]]
  name = "markets"
  url = "/markets/"
[[menu.main]]
  name = "email"
  url = "/email/"
[[menu.main]]
  name = "theming"
  url = "/theming/"
