baseURL = "https://mcclatchy.github.io/design"
title = "McClatchy Design"

languageCode = "en-us"
relativeURLs = true
disableLiveReload = true

summaryLength = 25

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "about us"
    title = "Who's on the team"
    url = "/about/"
    weight = 2
