---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/about
  label: About Us
  create: documents
  match: "**/*"
- type: directory
  path: data/team
  label: The Team
  create: none
  match: "*.toml"
- type: directory
  path: content/saratoga
  label: Saratoga
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.53'
