name: Deploy to Google Cloud Storage

# on:
#   push:
#     branches:
#       - main

on: workflow_dispatch

jobs:
  upload-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get minor version
        run: |
          export VERSION=$(jq '.version | sub(".[0-9]$"; "") | tonumber' < package.json)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Sync files to Google Cloud Storage
        run: |
          gcloud storage rsync --recursive dist gs://mc-high-impact/sds/$version
